version: '3.7'
services:
  minio:
    image: 'minio/minio:latest'
    container_name: minio
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '1034:9000'
      - '1036:9001'
    volumes:
      - /opt/volume/minio:/data
    env_file:
      - ./minio.env
    command: server --console-address :9001 /data
    #command: server --address 0.0.0.0:9001 /data

networks:
  mainframe:
    driver: bridge