version: '3.7'
services: 
    minio:
      image: minio/minio:latest
      container_name: minio
      ports:
        - 9001:9001
        - 9002:9002
      volumes:
        - /mnt/data/:/data
      environment:
        MINIO_ROOT_USER: oodlesadmin
        MINIO_ROOT_PASSWORD: oodlespass