version: '3.7'
services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    networks:
      - mainframe
    ports:
      - '1026:8000'
      - '1028:9000'
    volumes:
      - /opt/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  mainframe:
    driver: bridge            