version: '3.7'
services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    networks:
      - mainframe
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/docker/portainer:/data

networks:
  mainframe:
    driver: bridge            