version: '3.7'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    ports:
      - '80:80'
      - '8000:81'
      - '443:443'
    volumes:
      - /home/ubuntu/docker/npm-data/data:/data
      - /home/ubuntu/docker/npm-data/letsencrypt:/etc/letsencrypt