version: '3.7'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '80:80'
      - '1024:81'
      - '443:443'
    volumes:
      - /opt/volume/npm-app/data:/data
      - /opt/volume/npm-app/letsencrypt:/etc/letsencrypt

networks:
  mainframe:
    driver: bridge      