version: "3.7"
services:
  minio:
    image: minio/minio:latest
    container_name: minio-demo
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - oodles
    volumes:
      - ./volume/minio:/data
    env_file:
      - ./ENV/minio.env
    command: server --console-address :9001 /data
    #command: server --address 0.0.0.0:9001 /data
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    ports:
      - '8080:80'
      - '81:81'
      - '443:443'
    networks:
      - oodles      
    volumes:
      - ./volume/npm-app/data:/data
      - ./volume/npm-app/letsencrypt:/etc/letsencrypt
networks:
    oodles:    
