version: '3.7'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: unless-stopped   
    privileged: true
    user: root
    networks:
      - mainframe
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /opt/volume/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

networks:
  mainframe:
    driver: bridge