version: "3.7"
services:
  # NginxProxyManager #
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '80:80'
      - '1024:81'
      - '443:443'
    volumes:
      - /opt/volume/npm-app/data:/data
      - /opt/volume/npm-app/letsencrypt:/etc/letsencrypt

  # Portainer #
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    networks:
      - mainframe
    ports:
      - '1025:8000'
      - '1026:9000'
    volumes:
      - /opt/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # Jenkins #
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: unless-stopped   
    privileged: true
    user: root
    networks:
      - mainframe
    ports:
      - '1028:8080'
      - '1027:50000'
    volumes:
      - /opt/volume/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

networks:
  mainframe:
    driver: bridge