version: '3.7'
services:
  # NginxProxyManager #
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm-app
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '80:80'
      - '1024:81'
      - '443:443'
    volumes:
      - /opt/volume/npm-app/data:/data
      - /opt/volume/npm-app/letsencrypt:/etc/letsencrypt

  # Portainer #
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    networks:
      - mainframe
    ports:
      - '1026:8000'
      - '1028:9000'
    volumes:
      - /opt/volume/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # Jenkins #
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: unless-stopped   
    privileged: true
    user: root
    networks:
      - mainframe
    ports:
      - '1030:8080'
      - '1032:50000'
    volumes:
      - /opt/volume/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  minio:
    image: 'minio/minio:latest'
    container_name: minio
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '1034:9000'
      - '1036:9001'
    volumes:
      - /opt/volume/minio:/data
    env_file:
      - ./minio.env
    command: server --console-address :9001 /data
    #command: server --address 0.0.0.0:9001 /data      |

  # Grafana #
  grafanaa:
    image: 'grafana/grafana:latest'
    container_name: grafana
    restart: unless-stopped   
    user: root
    networks:
      - mainframe
    ports:
      - '1038:3000'
    volumes:
      - /opt/volume/grafana:/var/lib/grafana
    env_file:
      - ./grafana.env

  # Prometheus #
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    restart: unless-stopped
    user: root   
    networks:
      - mainframe 
    ports:
      - '1040:9090'
    volumes:
      - /opt/volume/prometheus:/prometheus
    command:
      - '--config.file=./prometheus.yml'

  # Node Exporter #
  node-exporter:
    image: 'quay.io/prometheus/node-exporter:latest'
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '1042:9100'      
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename:ro      

networks:
  mainframe:
    driver: bridge