version: '3.7'
services:
  grafanaa:
    image: 'grafana/grafana:latest'
    container_name: grafana
    restart: unless-stopped
    networks:
      - mainframe
    ports:
      - '3000:3000'
    volumes:
      - /opt/volume/grafana:/var/lib/grafana
    env_file:
      - ./grafana.env

networks:
  mainframe:
    driver: bridge      