global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  # Types of Job for timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus:1036

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter:1038
