version: '3.7'
services: 
    nginx:
      image: 'nginx:latest'
      container_name: nginx
      restart: unless-stopped
      hostname: nginx
      networks:
        - mainframe
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - /opt/volume/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  mainframe:
    driver: bridge
